### ISSUE TITLE
i cant build the 1.12.2 version

### ISSUE THREAD

**Issue by ThnksCJ** [THEREALWWEFAN231/WWEs-Altening-Mod#8]
C:\Users\EOL\Downloads\WWEs-Altening-Mod-e70949259689f89fc72645aeaccffc989fdc1fdb\WWEs-Altening-Mod-e70949259689f89fc72645aeaccffc989fdc1fdb>gradlew setupDecompWorkspace
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'WWEs-Altening-Mod-e70949259689f89fc72645aeaccffc989fdc1fdb'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find mixingradle.jar (org.spongepowered:mixingradle:0.6-SNAPSHOT).
     Searched in the following locations:
         http://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.6-SNAPSHOT/mixingradle-0.6-SNAPSHOT.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 45.341 secs

C:\Users\EOL\Downloads\WWEs-Altening-Mod-e70949259689f89fc72645aeaccffc989fdc1fdb\WWEs-Altening-Mod-e70949259689f89fc72645aeaccffc989fdc1fdb>

**Comment by dolphin-cat** [comment]
if you click the link it says 404, meaning the jar was removed from the forge servers, try contacting forge support.
